// Host verification for firmware/infer.c: bit-exact logits vs vectors.h
// (generated by ml/train.py) plus an inference latency benchmark.
// Build: gcc -O2 -Ifirmware -Itest test/main.c firmware/infer.c -o /tmp/tinfer && /tmp/tinfer
#include "infer.h"
#include "model.h"
#include "vectors.h"
#include <stdio.h>
#include <string.h>
#include <time.h>

static int argmax(const int8_t *lg) {
  int am = 0;
  for (int o = 1; o < NCLASS; o++)
    if (lg[o] > lg[am])
      am = o;
  return am;
}

int main(void) {
  int fail = 0;
  for (int v = 0; v < NVEC; v++) {
    int8_t lg[NCLASS];
    int am = infer(VX + v * IN_C * WIN, lg);
    if (memcmp(lg, VL[v], NCLASS) != 0 || am != argmax(VL[v])) {
      fail = 1;
      printf("vec %d MISMATCH\n got:", v);
      for (int o = 0; o < NCLASS; o++)
        printf(" %d", lg[o]);
      printf("\nwant:");
      for (int o = 0; o < NCLASS; o++)
        printf(" %d", VL[v][o]);
      printf("\n");
    }
  }
  printf("%s (%d vectors)\n", fail ? "FAIL" : "PASS", NVEC);

  // host CPU reference point; on-device latency is printed over Serial
  struct timespec a, b;
  int8_t lg[NCLASS];
  int reps = 1000;
  clock_gettime(CLOCK_MONOTONIC, &a);
  for (int r = 0; r < reps; r++)
    infer(VX, lg);
  clock_gettime(CLOCK_MONOTONIC, &b);
  double us = ((b.tv_sec - a.tv_sec) * 1e6 + (b.tv_nsec - a.tv_nsec) / 1e3) / reps;
  printf("host infer: %.1f us avg over %d reps\n", us, reps);
  return fail;
}
